# Generated by Django 3.1.4 on 2020-12-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksapp',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
