# Generated by Django 3.1.4 on 2020-12-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0004_tracksapp_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksapp',
            name='image',
            field=models.ImageField(default='', upload_to='tracks/'),
            preserve_default=False,
        ),
    ]
