# Generated by Django 3.1.4 on 2020-12-26 17:59

from django.db import migrations, models
import tracksapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0005_tracksapp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksapp',
            name='trackpath',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracksapp',
            name='image',
            field=models.ImageField(upload_to=tracksapp.models.image_upload),
        ),
    ]
