# Generated by Django 3.1.4 on 2020-12-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0008_remove_tracksapp_trackpathname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksapp',
            name='pathname',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
