# Generated by Django 3.1.4 on 2020-12-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0010_auto_20201227_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksapp',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
