# Generated by Django 3.1.4 on 2020-12-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0013_auto_20201229_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='learInEnglish',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='learnInArabic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='w3shools',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
