# Generated by Django 3.1.4 on 2020-12-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0014_auto_20201230_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course',
        ),
        migrations.AddField(
            model_name='tracksapp',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksapp.courses'),
        ),
    ]
