# Generated by Django 3.1.4 on 2020-12-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0016_auto_20201230_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
    ]
