# Generated by Django 3.1.4 on 2020-12-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0011_tracksapp_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('track', models.ManyToManyField(to='tracksapp.tracksapp')),
            ],
        ),
    ]
