# Generated by Django 3.1.4 on 2020-12-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0017_remove_courses_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='learInEnglish',
            new_name='firstcourse_url',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='learnInArabic',
            new_name='secondcourse_url',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='w3shools',
            new_name='thirdcourse_url',
        ),
        migrations.AddField(
            model_name='courses',
            name='firstcourse_title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='secondcourse_title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='thirdcourse_title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
