# Generated by Django 3.1.4 on 2020-12-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0019_auto_20201230_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='firstcourse_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='secondcourse_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
