# Generated by Django 3.1.6 on 2021-02-15 11:50

from django.db import migrations, models
import django.db.models.deletion
import tracksapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksapp', '0021_auto_20210215_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='firstcourse_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Course Title'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='firstcourse_url',
            field=models.URLField(blank=True, null=True, verbose_name='First Course URL'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='secondcourse_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Second Course Title'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='secondcourse_url',
            field=models.URLField(blank=True, null=True, verbose_name='Second Course URL'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='thirdcourse_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Third Course Title'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='thirdcourse_url',
            field=models.URLField(blank=True, null=True, verbose_name='Third Course URL'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Courses Name'),
        ),
        migrations.AlterField(
            model_name='tracksapp',
            name='background_in_detail',
            field=models.ImageField(upload_to=tracksapp.models.image_upload_detail, verbose_name="Background Image in Track's page"),
        ),
        migrations.AlterField(
            model_name='tracksapp',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracksapp.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tracksapp',
            name='description_in_detail',
            field=models.TextField(max_length=1000, verbose_name="Description inside Track's Page"),
        ),
        migrations.AlterField(
            model_name='tracksapp',
            name='description_in_list',
            field=models.TextField(max_length=1000, verbose_name='Description in Home'),
        ),
        migrations.AlterField(
            model_name='tracksapp',
            name='image_in_list',
            field=models.ImageField(upload_to=tracksapp.models.image_upload, verbose_name='Image in Home'),
        ),
        migrations.AlterField(
            model_name='tracksapp',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Track Name'),
        ),
    ]
