# Generated by Django 3.1.7 on 2021-02-22 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracksapp', '0023_courses_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='like',
        ),
        migrations.AddField(
            model_name='courses',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
