# Generated by Django 3.1.6 on 2021-02-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210218_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile/default.jpg', upload_to='profile/'),
        ),
    ]
