# Generated by Django 3.1.6 on 2021-02-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210219_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../media/profile/default.jpg', upload_to='profile/'),
        ),
    ]
