# Generated by Django 3.1.6 on 2021-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210219_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../static/default/default.jpg', upload_to='profile/'),
        ),
    ]
