# Generated by Django 3.1.6 on 2021-02-19 15:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210219_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=accounts.models.image_url, upload_to='profile/'),
        ),
    ]
